sources:
  - name: Mintbase
    handler:
      graphql:
        endpoint: "https://interop-testnet.hasura.app/v1/graphql"
    transforms:
      - rename:
          renames:
            - from:
                type: nft_metadata
              to:
                type: Thing
      - typeMerging:
          queryFields:
            - queryFieldName: nft_metadata
              keyField: id
              keyArg: reference
  - name: everything
    handler:
      graphql:
        endpoint: "http://localhost:4050/graphql"
    transforms:
      - typeMerging:
          queryFields:
            - queryFieldName: thing
              keyField: id

additionalTypeDefs: |
  """
  Describes the authentication object as provided by Auth0.
  """
  type AuthenticationInfo {
    """
    String that uniquely identifies an authenticated user.
    """
    sub: String!
  }
 
  extend type Query {
    """
    The authentication information of the request.
    """
    authInfo: AuthenticationInfo
  }
additionalResolvers:
  - ./additionalResolvers.ts
plugins:
  - auth0:
      domain: 'dev-nhpdvemm.us.auth0.com'
      audience: 'https://dev-nhpdvemm.us.auth0.com/api/v2/'
      extendContextField: '_auth0'
      preventUnauthorizedAccess: false
